### ISSUE TITLE
Send Time to KNX bus

### ISSUE THREAD

**Issue by Julius2342** [XKNX/xknx#11]
We have to send the time to the KNX bus to display it properly within my [GIRA Tastsensor 3 Plus 2-fach 514200 ](https://katalog.gira.de/de_DE/datenblatt.html?id=635019)

Open question:

- Is time a device? 
- Do we send UTC or do they use local time
- How should the configuration look like

````
    time:

        Time_1:
            group_address: "1/2/7"
            time_zone: "Europe/Berlin"  # If the bus needs local time
            frequency: 20 # send every 20 seconds
`````
 
Alternatively we could put the timing to the hass_component (using this utc_changed ... function)
