### ISSUE TITLE
Climate operation mode set to Sleep after HA restart 

### ISSUE THREAD

**Issue by alphasixtyfive** [XKNX/xknx#1550]
**Description of problem:**

- [ ] using xknx standalone
- [X] using Home-Assistant knx integration

**Version information:**
- xknx / Home-Assistant release with the issue: 2024.8.2
- last working xknx / Home-Assistant release (if known): Unsure, perhaps 2024.7.X

**Problem-relevant `configuration.yaml` entries (fill out even if it seems unimportant):**

![image](https://github.com/user-attachments/assets/346a83af-381a-432e-a277-9bd359ca0cee)

```
  climate:
    - name: Hallway
      temperature_step: 0.5
      temperature_address: 4/6/1
      target_temperature_state_address: 4/5/1
      setpoint_shift_address: 3/3/1
      setpoint_shift_state_address: 4/3/1
      operation_mode_address: 3/1/1
      controller_status_state_address: 4/0/1
      operation_modes:
        - Comfort
        - Standby
        - Night
        - Frost Protection
```

I've tried commenting out `operation_modes` but that didn't do anything apart from adding "None" as a mode.

On start I see it is reading `[0x21]` from the bus during startup, but I'm not sure what this value translates to since this is Jung Room controller for which years ago @farmio had worked hard to add `controller_status_state_address`:

```
2024-08-19 12:23:27.783 DEBUG (MainThread) [xknx.cemi] Incoming CEMI: <CEMIFrame code="L_DATA_IND" info="CEMIInfo("")" data="CEMILData(src_addr="IndividualAddress("1.1.1")" dst_addr="GroupAddress("4/0/1")" flags="1011110011100000" tpci="TDataGroup()" payload="<GroupValueResponse value="<DPTArray value="[0x21]" />" />")" />
```
