### ISSUE TITLE
reset_after for binary_sensor blocks bus writing

### ISSUE THREAD

**Issue by FredericMa** [XKNX/xknx#298]
**Description of problem:**

- [ ] using xknx standalone
- [x] using Home-Assistant knx plugin

I have an automation to bypass any opened window in the house in order to arm our alarm system if any are open.

Sequence is like this:
- We press a  button on a KNX actuator (see yaml below) that will trigger an automation.
- The automation sends command to the alarm system to bypass every open window via MQTT.
- If all is OK, the alarm sends a "ready to arm" message back via MQTT.
- This triggers another automation that switches a KNX switch to toggle a LED on the KNX actuator.

Although the last step in sequence above is triggered aprox. 3 seconds later, the LED only toggles 10 seconds after the first step. This is exactly the configured "reset_after" delay that is configured for the binary_sensor used in the first step of the sequence describe above.

I supose this line is causing the blocking:
https://github.com/XKNX/xknx/blob/3ab0a53e334e2c55949b57a3e6704466c87e7cf7/xknx/devices/binary_sensor.py#L159

**Version information:**
- xknx / Home-Assistant release with the issue: 0.110.4
- last working xknx / Home-Assistant release (if known):

**KNX installation:**

**Problem-relevant `xknx.yaml` or `configuration.yaml` entries (fill out even if it seems unimportant):**
```yaml
  - platform: knx
    name: alarm_bypass_windows
    address: '6/3/2'
    reset_after: 10000 # Reset after 10 seconds to ignore double presses.
    sync_state: false
```

**Traceback (if applicable):**
