### ISSUE TITLE
Future of xknx and the custom home assistant component

### ISSUE THREAD

**Issue by marvin-w** [XKNX/xknx#379]
I'd like to discuss the future of the xknx library in this ticket.

I feel like we should talk about the next steps concerning the library and the integration and also talk about some of the pitfalls that we usually encounter during development. (imho)

# Pitfalls and potential solutions

* When adding additional configurable features it is a burden to maintain them twice - once for the `xknx.yaml` and once for the custom HA component.

Sol.: Since HA is effectively going away from the YAML config we could think about removing _***all***_  platform YAML configurations and completely moving to `xknx.yaml`.

* User experience is not that great when using the knx integration inside HA

Sol.: HA is supporting config flows (see #238). We could make use of them and get rid of all the YAML configuration inside the HA component.

# Next steps

This list is sorted in chronological order but is not (yet?) complete and will probably change in the future.

1. Implement a `version` attribute in `xknx.yaml` and set the default version to 1. We can then start implementing a working draft for a future version of the configuration (version 2) that will then also replace the Home Assistant yaml configuration.

**Why**: The current structure of `xknx.yaml` is not straight forward to understand and doesn't look good. We should align it to HA standards.

2. Start implementing a working draft for version 2 of `xknx.yaml`. @farmio already had a couple of ideas how we can improve the current configuration style. The new configuration layout should add schema validation with voloptous (I don't know how to write that awkward word jesus) (like HA does it).

Potential new layout:

```
light:
    - name: "kitchen"
      friendly_name: "Kitchen" # used as friendly name attribute in HA
      on_off:
        address: "1/2/3"
        state_address: "1/2/4"
        state_update: "every 90" # for setting state_updater
      brightness:
        address: "1/3/3"
        state_address: "1/3/4"
        state_readable: True # shall answer to GroupValueRead - mutually exclusive with state_update
        passive_state: ["3/4/5", "3/4/9"]

climate:
    - name "kitchen"
      friendly_name: "Kitchen"
      setpoint_shift:
        address: "1/2/3"
        state_address: "1/2/4"
        mode: "DPT9.001"
```

**Why**: We should use versioning here in order to not conflict with current user configurations. Also, by doing this we could effectively use smaller pull requests which are easier to review. The new layout can also cover new features like **passive state addresses** (for listening GAs - used for i.e. central functions), for globally using and configuring the new **state updater** and also for adding a custom **friendly name** (no more customization.yaml yay).

3. (Optional) Implement a migration tool for users to use in order to convert there `xknx.yaml` into the new version.

**Why**: Users will probably be annoyed by always moving configs back and forth. We should assist them here. We could even think of integrating this directly in xknx and just do the necessary conversion _on the fly_  when we detect that a user still uses an old version. And then after some time we can drop the old config completely.

4. (Optional) Implement a migration tool for users that use the HA YAML configs.

**Why**: They need to be migrated to `xknx.yaml` version 2.

5. Drop YAML Support for Home Assistant component.

**Why**: Users can use `xknx.yaml` then. We have less maintenance effort and we can use the discovery features from home assistant for it. 

6. Implement a config flow

**Why**: A config flow allows us to use the `GatewayScanner` to search for new devices. Users will then be able to configure the KNX integration in the frontend. Please note that they can **only** configure the connections parameters. Nothing else.

Todos:

- [ ] Check if this approach works with the available discovery options for HA

7. Drink some beer, this is gonna be a shit ton of work. :100:
