### ISSUE TITLE
Sensors won't work

### ISSUE THREAD

**Issue by sagitt** [XKNX/xknx#486]
**Description of problem:**

- [ ] using xknx standalone
- [x] using Home-Assistant knx plugin

**Version information:**
- xknx / Home-Assistant release with the issue: n/a
- last working xknx / Home-Assistant release (if known): n/a

**Problem-relevant `xknx.yaml` or `configuration.yaml` entries (fill out even if it seems unimportant):**

After upgrade to home assistant 0.117 sensor before working, now won't work.. like energy meter

![Schermata 2020-10-29 alle 00 02 06](https://user-images.githubusercontent.com/169086/97506018-4dfc0a80-197a-11eb-9328-ba9c6a257649.png)

```
    # Energia [Rilevato]
    - name: 'Energia [Potenza Attiva]'
      state_address: '7/0/0'
      sync_state: true
      type: 'power'
    - name: 'Energia [Potenza Reattiva]'
      state_address: '7/0/1'
      sync_state: true
      type: 'electric_potential'
    - name: 'Energia [Tensione]'
      state_address: '7/0/2'
      sync_state: true
      type: 'electric_potential'
    - name: 'Energia [Corrente]'
      state_address: '7/0/3'
      sync_state: true
      type: 'electric_current'
    - name: 'Energia [Fattore Di Potenza]'
      state_address: '7/0/4'
      sync_state: true
      type: 'powerfactor'
    - name: 'Energia [Frequenza]'
      state_address: '7/0/5'
      sync_state: true
      type: 'frequency'
```

**Comment by farmio** [comment]
🔮 Please provide more information. 
- Which version were you running before, when it worked?
- Paste log messages! Setting xknx.log to debug level would probably help. 
- Does anything else work? Eg sending to bus, updating states of a light etc.

**Comment by sagitt** [comment]
> 🔮 Please provide more information.
> 
> * Which version were you running before, when it worked?
> * Paste log messages! Setting xknx.log to debug level would probably help.
> * Does anything else work? Eg sending to bus, updating states of a light etc.

Last really working Hass is 0.114,

0.115 add binary sensor bug, disconnections bug, bad warning bug (https://github.com/XKNX/xknx/issues/474)
0.116 fix binary sensor bug, disconnections and bad warning still
0.117 disconnections to test, bad warning still and no energy meter sensor works

yes, other "sensors" like my covers %, "binary sensors" like alarm works. only energy meter won't work. downgrading to 0.116 make it works. for example image below, are "sensors". Turn on\off lights, up\down\% covers etc. works fine. i not tested every configured item but these works.

```
sensor:
    # Tapparelle
    # Cucina
    - name: 'Stato Tapparella [Cucina]'
      state_address: '2/2/0'
      sync_state: 'init'
      type: 'percent'
    # Soggiorno
    - name: 'Stato Tapparella [Soggiorno]'
      state_address: '2/2/1'
      sync_state: 'init'
      type: 'percent'
    # Camera 3
    - name: 'Stato Tapparella [Camera 3]'
      state_address: '2/2/2'
      sync_state: 'init'
      type: 'percent'
    # Bagno
    - name: 'Stato Tapparella [Bagno]'
      state_address: '2/2/3'
      sync_state: 'init'
      type: 'percent'
    # Camera 2
    - name: 'Stato Tapparella [Camera 2]'
      state_address: '2/2/4'
      sync_state: 'init'
      type: 'percent'
    # Camera 1
    - name: 'Stato Tapparella [Camera 1]'
      state_address: '2/2/5'
      sync_state: 'init'
      type: 'percent'

```
![Schermata 2020-10-29 alle 10 00 27](https://user-images.githubusercontent.com/169086/97547058-a14b7880-19cd-11eb-94d1-aaffaa51dd83.png)

i'll make a log soon.
