### ISSUE TITLE
Brightness state address not used to reflect the current brightness value of lights.

### ISSUE THREAD

**Issue by nkvoll** [XKNX/xknx#513]
**Description of problem:**

- [ ] using xknx standalone
- [x] using Home-Assistant knx plugin

I have some lights that when switched on, go to 100%, regardless of prior dimmed value. If I set the dimming in HA to 41%, then turn the light off and on again, the physical lights will go to 100% while in HA the brightness is set to `105` (out of 255).

**Version information:**
- xknx / Home-Assistant release with the issue: 0.118.3
- last working xknx / Home-Assistant release (if known): N/A

**KNX installation:** N/A I think

**Problem-relevant `xknx.yaml` or `configuration.yaml` entries (fill out even if it seems unimportant):**

The lights are defined like this:

```
  light:
    - name: basement-light-living-room
      address: "2/4/0"
      state_address: "2/4/1"
      brightness_address: "2/4/2"
      brightness_state_address: "2/4/3"
```

After setting HA brightness to 105, then turning the lights off and on again, this is the KNX state:

![image](https://user-images.githubusercontent.com/391931/100521086-c5070780-31a1-11eb-98df-f6342b220c83.png)

While HA thinks the state is `on` with the following attributes:

```
brightness: 105
friendly_name: basement-light-living-room
supported_features: 1
```

**Traceback (if applicable):** N/A
