### ISSUE TITLE
Feature request : Cover remote values in Home Assistant & Possibility to restore their state in Home Assistant

### ISSUE THREAD

**Issue by CharlieBailly** [XKNX/xknx#521]
Dear all,
Unfortunately, there are still KNX covers with no state addresses, which means Home Assistant only knows the real state when a move_address is on the KNX bus. There are two problems here according to me :

1. Only one move_address can change this state and if you have multiple buttons that pulls up or down your cover with different move_addresses, Home Assistant will not update the state of the cover when using these buttons.
2. Even if you are lucky and you have only one move_address that your cover is listening to on the KNX bus, if you restart Home Assistant, the state of the cover is lost since it is not recovered by Home Assistant since the cover do not have a position_address.

I am actually using a custom xknx version in Home Assistant to solve theses two issues, do you think it is worth it to make a pull request to add theses functionalities ?

Here is a sample configuration I am using :

```yaml
xknx:
  ...
  ...
  cover:
    - name: "Volet petite chambre"
      travelling_time_up: !secret travelling_time_up_large
      travelling_time_down: !secret travelling_time_down_large
      move_long_address: "2/4/0" #This one is used to actually send the KNX payload to move up and down the cover
      stop_address: "2/4/1" #This one is used to actually send the KNX payload to stop the cover
      move_long_remote_addresses: #Home assistant is listening to these adresses to update the cover state (up/down)
        - "24/4/23"
        - "10/4/226"
        - "24/4/45"
      stop_remote_addresses: #Home assistant is listening to these adresses to update the cover state (stop)
        - "24/4/24"
        - "10/4/225"
        - "24/4/46"

```
I am also implicitly Restoring the state of the covers (they inherit from the RestoreEntity in Home Assistant in my custom xknx components) but maybe we could add a boolean value in the cover config as well such as :

```yaml
restore_value: true # or false (and maybe true by default if you use move_long_remote_addresses/stop_remote_addresses )
```
Tell me what do you think of it ?
Thanks
