### ISSUE TITLE
DPT 13.013 not support float

### ISSUE THREAD

**Issue by pasarn** [XKNX/xknx#525]
**Description of problem:**

I use an MDT AMI Actor to get my energy consumption in kWh. The MDT send the value as float.

> DecodedDpValue | 1,401298E-45

I have access to ETS5.

- [ ] using xknx standalone
- [X] using Home-Assistant knx plugin

**Version information:**
- Home-Assistant release with the issue:  0.118.5

**KNX installation:**

- AMI-1216.02 Schaltaktor mit Strommessung 12-fach, 12TE, 16/20A
- KNXD as Gateway
- Hassio on RPI

**Problem-relevant `xknx.yaml` or `configuration.yaml` entries (fill out even if it seems unimportant):**
```
knx:
  tunneling:
    host: '192.168.x.x'
    port: 3671
    local_ip: '192.168.x.x'
  sensor:
    - name: Testbrett.kwhHeizung
      state_address: '1/2/1'
      sync_state: False
      type: 'active_energy_kwh'

```
**Traceback (if applicable):**
