### ISSUE TITLE
Instable connection to GIRA KNX IP Router 2167

### ISSUE THREAD

**Issue by stieler-it** [XKNX/xknx#540]
**Description of problem:**

- [ ] using xknx standalone
- [x] using Home-Assistant knx plugin

I want to migrate my home automation from a rather complex Node-RED based solution to Home Assistant. I have setup Home Assistant on a Raspberry Pi 3 with Supervisor and want to migrate basically room by room. Raspberry is connected via LAN to my network and the KNX IP Router. xknx works perfect and also fast, but after a time it seems to lose it's connection. Since all our lights are controlled by KNX you can imagine how the WAF looks like currently.

What do I see? In the log there are `Heartbeat to KNX bus failed. Reconnecting.` from time to time. Maybe once in an hour.  Today there was also a `Could not connect to KNX. Retry in 3 seconds.` but I don't remember having seen that the other days. This morning our switches did not work, but as soon as I sent a command from Home Assistant this apparently fixed the connection and switches worked again. Restarting Home Assistant or waiting for a while also fixes the problem until it occurs again.

What have I tried already?
* `state_updater: false` because I thought maybe there is too much traffic or a problem with the knkx queue since a lot of my KNX devices do not react on read requests that are sent
* Switching off Node-RED so only knkx is talking to the KNX IP Router

My feeling is that the keepalive is somehow not working here, or it is not aggresive/fast enough. This doesn't really explain why the connection breaks, though. My Node-RED setup using [knx-ultimate node](https://flows.nodered.org/node/node-red-contrib-knx-ultimate) just works (I don't know if there are also reconnects, though).

**Version information:**
- xknx / Home-Assistant release with the issue: 2020.12.7
- last working xknx / Home-Assistant release (if known): Never worked for me

**KNX installation:**
* GIRA KNX IP Router 2167
* Different sensors/actors but they are all affected as soon as the connection broke.

**Problem-relevant `xknx.yaml` or `configuration.yaml` entries (fill out even if it seems unimportant):**

```
knx:
  tunneling:
    host: '192.168.178.104'
    port: 3671
  binary_sensor: !include knx_binary_sensor.yaml
  cover: !include knx_cover.yaml
  expose: !include knx_expose.yaml
  light: !include knx_light.yaml
  sensor: !include knx_sensor.yaml
  switch: !include knx_switch.yaml
  state_updater: false

```
**Traceback (if applicable):**

`Heartbeat to KNX bus failed. Reconnecting.
Logger: xknx.log
Source: /usr/local/lib/python3.8/site-packages/xknx/io/tunnel.py:288`
