### ISSUE TITLE
Central dimmers should not have any "is_open" or "is_closed" state

### ISSUE THREAD

**Issue by Julius2342** [XKNX/xknx#6]
For central covers/shutters it is not possible to determine a general is_open or is_closed state. Therefore both values have to return a None.

To make this possible, central dimmers have to be marked as such in the configuration.

**Comment by twistermcneal** [comment]
if we own all devices, i think we can loop thru all devices, and get the current position of a defined group
something in the config like groupId = A for each device 
the central shutter use this id to get the right states
just my two cents

**Comment by Julius2342** [comment]
A very old issue :)

I think the KNX concept of having a central switch conflicts with the HASS approach.

I solved this in my setup by not using a central KNX address but instead having a KNX-binary input and then switching all lights on/off all covers up/down.

This also has the advantage, that all states (of each light/cover) is instantly available within hass.

**Comment by spali** [comment]
Yes, I know it's really old, but wonder why not more people have this "problem".
It's one of the base model how to solve central functions in KNX except scenes.

I'm thinking about to solve it by scenes, but I hassle with that, because it costs scene numbers in KNX and makes it a lot harder to maintain in KNX.

Still think something generic like the "stateless" option could be a real improvements, but don't know if HA can support this out of the box.

But I'm curious about how you solved it... what do you mean with "KNX-binary input"?
Take your time with the answer, I don't want to disturb you on your traveling ;)

**Comment by Julius2342** [comment]
This example turns on/off the hue_strips when pressed once and all lights in the house if pressed twice: 

```
- platform: knx
  name: Sleeping.SwitchLeft
  address: '5/0/6'
  automation:
    - counter: 1
      hook: 'on'
      action:
       - entity_id: light.hue_lightstrip_1
         service: homeassistant.turn_on
       - entity_id: light.hue_lightstrip_2
         service: homeassistant.turn_on
       - entity_id: light.hue_lightstrip_3
         service: homeassistant.turn_on
    - counter: 2
      hook: 'on'
      action:
       - service: light.turn_on

- platform: knx
  name: Sleeping.SwitchRight
  address: '5/0/7'
  automation:
    - counter: 1
      hook: 'on'
      action:
        - entity_id: light.hue_lightstrip_1
          service: homeassistant.turn_off
        - entity_id: light.hue_lightstrip_2
          service: homeassistant.turn_off
        - entity_id: light.hue_lightstrip_3
          service: homeassistant.turn_off
    - counter: 2
      hook: 'on'
      action:
        - service: light.turn_off
```
