### ISSUE TITLE
Must always sleep after every interaction with the bus

### ISSUE THREAD

**Issue by tails4e** [XKNX/xknx#622]
**Description of problem:**
Every time I issue a command to the bus it works, but only if I use "await asyncio.sleep(2)" before the next command - 
i.e. if I do:
```
     temp  = xknx.devices[1]
     await temp.sync() # Syncs the state. Tries to read the corresponding value from the bus.
     print(temp.resolve_state())
```

I get a temperature of None - but if I sleep before it works.
```
     temp  = xknx.devices[1]
     await temp.sync() # Syncs the state. Tries to read the corresponding value from the bus.
     await asyncio.sleep(2)
     print(temp.resolve_state())
```
 

Similarly if I try to turn on 2 lights without having a sleep between them, it fails. I don't mind working around this by adding a delay to every call, but it seems like this should be unnecessary

- [ x] using xknx standalone
- [ ] using Home-Assistant knx plugin

**Version information:**
- xknx / Home-Assistant release with the issue: 0,17
- last working xknx / Home-Assistant release (if known): NA

**KNX installation:**

**Problem-relevant `xknx.yaml` or `configuration.yaml` entries (fill out even if it seems unimportant):**
```
general:
  own_address: "1.1.120"

connection:
  tunneling:
    gateway_ip:   "192.168.1.149"
    gateway_port: "3671"
    local_ip:     "192.168.1.167"

groups:
  light:
    Living-Room.Light_1: { group_address_switch: "1/1/16" }

  time:
    General.Time: { group_address: "1/1/100" }

  sensor:
    Cinema.Temperature: {group_address_state: '1/1/101', value_type: 'temperature'}
```

**Traceback (if applicable):**
