### ISSUE TITLE
KNX Cover State not correct in HASS

### ISSUE THREAD

**Issue by FireFrei** [XKNX/xknx#70]
When restarting HASS (0.54.0) my KNX covers (actors are made by ABB) show an incorrect state - actually they are open, but hass says closed. 
I verified group addresses, I think they are correct. Object is marked as readable in ETS.

The abb documentation says:

```
 "Status Höhe/Lamelle 0…255" 1 Byte 
Der Ausgang sendet die relative Position des Behangs und die Lamellenstellung auf zwei getrennten Kommunikationsobjekten jeweils als 1-Byte-Wert (0…255). Für die Position des Behangs gilt: Der Wert 0 entspricht der Position oben (0 %). Der Wert 255 entspricht der Position unten (100 %).  
```

I tried to set the "invert_position" flag to "true" in hass, but:
- On hass startup, cover is still shown as closed but is actually opened
- Movement of covers is now inverted (Button "down" -> cover goes up)

I did not notice any knx errors regarding xknx covers in the hass logs.
When I move the knx cover manually (by a native knx switch/button) the state is updated correctly in hass, after the cover has stopped.

Edit: 
My Hass config:
```
cover:
  - platform: knx
    name: 'eg_wohnzimmer_fenster'
    move_long_address: '1'
    move_short_address: '2'
    position_address: '3'
    position_state_address: '4'
```
