### ISSUE TITLE
Light entity reports incomplete supported color modes

### ISSUE THREAD

**Issue by crazyfx1** [XKNX/xknx#842]
**Description of problem:**
I have a light which supports color and color_temperature. Both addresses are set.

But the light entity only reports one of the modes as supported color modes. The entity should report all supported modes.

If both color and color_temp are set, the following state is reported:
```yaml
supported_color_modes:
  - rgb
friendly_name: Schlafzimmer Licht
supported_features: 0
```

If I remove the color part, the color_temp is returned:
```yaml
min_mireds: 166
max_mireds: 370
supported_color_modes:
  - color_temp
friendly_name: Schlafzimmer Licht
supported_features: 0
```

The hue integration for example reports both types:
```yaml
min_mireds: 153
max_mireds: 500
supported_color_modes:
  - color_temp
  - xy
```

- [ ] using xknx standalone
- [x] using Home-Assistant knx plugin

**Version information:**
- xknx / Home-Assistant release with the issue: 2021.12.5

**KNX installation:**
Not relevant

**Problem-relevant `configuration.yaml` entries (fill out even if it seems unimportant):**
```yaml
    - name: "Schlafzimmer Licht"
      address: '2/1/17'
      state_address: '2/2/17'
      brightness_address: '2/3/17'
      brightness_state_address: '2/4/17'
      color_temperature_address: '3/1/17'
      color_temperature_state_address: '3/2/17'
      color_temperature_mode: absolute
      color_address: '3/3/17'
      color_state_address: '3/4/17' 
```

**Traceback (if applicable):**
